---

- name: Download awscliv2 installer.
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: yes
    creates: /tmp/aws
    mode: preserve

- name: Run the installer.
  command:
  args:
    cmd: /tmp/aws/install
    creates: /usr/local/bin/aws
  become: true
  register: aws_install

- name: "Show installer output."
  debug:
    var: aws_install
    verbosity: 2
